services:
  backend:
    build: services/backend/.
    container_name: cirrus-backend
    restart: always
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - cirrus

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cirrus

networks:
  cirrus:
